language: generic

sudo: false

env:
  global:
  - HUGO_VERSION=0.52

before_install:
  # Install Hugo
  - mkdir -p bin
  - curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -o bin/hugo.tar.gz
  - tar xzvvf bin/hugo.tar.gz -C ./bin

script:
  - "./bin/hugo"

before_deploy:
  # Set up git user name and tag this commit
  #- git config --local user.name "YOUR GIT USER NAME"
  #- git config --local user.email "YOUR GIT USER EMAIL"
  - git tag "$(date +'%Y%m%d_%H%M%S')-$(git log --format=%h -1)"
  - tar cjvf public.tar.bz2 public/

deploy:
  - provider: pages
    skip-cleanup: true
    github-token:
      secure: MeyJiUIKuPO1XGzSUy9LWPmdRNQwFT++gmhy3+JMfcb0Ib7RE8JKkvHqXpCDnQ+HFb+cSww2rXFZc/E+76Hqf8Lg/V1l0JhWEmdsd4jumwPhzfAnN+gU5K7ZO4aXT7VvAswM8AmN4GxHO9g79qr/31VztqtRs9X48iFpaYPknuQCFnMWz9wedpIuAzzKsuKd6PYXzgs+v7senFIfPv4CZc90h2u0Sb1rv5IfSPeWOz6jFHCdZDbpdmahPexHCuOqLdJNeclvCW9iFpvvCmL4bGXFyNiORyCOFxtxZqvm+VVtkdXY4v5O6+4PYL6OxgQTsM0sbqbSXzWdRMj2KYVYYGMdLknaVgN+ObZ0t8laMUy/v2a8kspN2qerQjC/yjsh8WGeGHnfyCXFMvdPOCJXCbL9HPP6oKg2Qo1GErFRJww+7jrLYN+brTb0yl/4ar+oAh08Cseo7MIyKJ6OvgpSYX4xp85t4NHAtFn9Qy13QLH80OBnPYk6CrGPpN/ALQxTKW5CzRfNoDGTVVVIMb7tcDwiwZ5xKgeb30bgOLn/S0hEJnS71EJa0xhILJyZmWbzz20m5HQxsjglHDcO+HRoACX6d7ATTTx3d+d5qV0OUALFSdq7RhCYSp3NCBcqkiDD9godKlypgC2xmg+YHo1DA8+LSXAAhBBo0uVufymMHpc=
    keep-history: true
    local-dir: public
    on:
      branch: master
    target-branch: gh-pages
  - provider: releases
    api_key:
      secure: MeyJiUIKuPO1XGzSUy9LWPmdRNQwFT++gmhy3+JMfcb0Ib7RE8JKkvHqXpCDnQ+HFb+cSww2rXFZc/E+76Hqf8Lg/V1l0JhWEmdsd4jumwPhzfAnN+gU5K7ZO4aXT7VvAswM8AmN4GxHO9g79qr/31VztqtRs9X48iFpaYPknuQCFnMWz9wedpIuAzzKsuKd6PYXzgs+v7senFIfPv4CZc90h2u0Sb1rv5IfSPeWOz6jFHCdZDbpdmahPexHCuOqLdJNeclvCW9iFpvvCmL4bGXFyNiORyCOFxtxZqvm+VVtkdXY4v5O6+4PYL6OxgQTsM0sbqbSXzWdRMj2KYVYYGMdLknaVgN+ObZ0t8laMUy/v2a8kspN2qerQjC/yjsh8WGeGHnfyCXFMvdPOCJXCbL9HPP6oKg2Qo1GErFRJww+7jrLYN+brTb0yl/4ar+oAh08Cseo7MIyKJ6OvgpSYX4xp85t4NHAtFn9Qy13QLH80OBnPYk6CrGPpN/ALQxTKW5CzRfNoDGTVVVIMb7tcDwiwZ5xKgeb30bgOLn/S0hEJnS71EJa0xhILJyZmWbzz20m5HQxsjglHDcO+HRoACX6d7ATTTx3d+d5qV0OUALFSdq7RhCYSp3NCBcqkiDD9godKlypgC2xmg+YHo1DA8+LSXAAhBBo0uVufymMHpc=
    file: public.tar.bz2
    skip_cleanup: true
    on:
      branch: master

# whitelist
branches:
  only:
    - master 
