language: generic

sudo: false

env:
  global:
  - HUGO_VERSION=0.52
  - secure: "hguvp7Bn8BFpJTU5KdQY16vNozm+0kBkBrFkSw+5e0Nu4KzsA79RJVxQ1Ad1iRFKFixLZ6C7KKHFY42q+RO8XLmYdIXSbi454Qr38AULYN19Cjzrepff3cwaY2fJUszJd1ytyOc1BDbSSSNbCa1yapkAqq+cCsCpynuexwBIrQtOS7I3HFF1cuGxT1jvX+zcsJhbiAcR0U1iwhgeK0Tl4hJSBhijRGKenEfe6nZigynwAdgQ6MBs1gFrE82QP4atWfhp7mBRgyYR8F51wSquVWhRQPQBxXyCvtU03P2S+uUAPTeJ/FfMiWGxAgy1Mp6z57P7rxA7NJQsTWdUecRz7q2nTB9FdbvULdCQ5KZ28EIPFFsaTS+IwfxV3vjDeE8/6ortryCysXN28sIdBl1tfBmnFMoN52kmu1L7j0OwDF1aIfzotwskyUi6QioQysGVfOQ5cdX7NrV8GkhDk04YzoTys0Z/jc5Ur0FmUKFC+IHzlMgK7AJ3IJQInl3drErMm36wO0nlgJ0vlPakxfsbXxBrnMBKK4TlV3Fup0Rm+EuajcmaUeJlJZ3ko1+SRTtVnnmdldvrsCGmjIoqiBQjIIeE/IfPj+r1etD6D/rcbDPFl+MhTSiHZr40hvHlaZinLN7Q8Yf1QAxyXADiSikh/samuulB6MOhZAy7nvdwo7I="

before_install:
  # Install Hugo
  - mkdir -p bin
  - curl -L https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -o bin/hugo.tar.gz
  - tar xzvvf bin/hugo.tar.gz -C ./bin

script:
  - "./bin/hugo"

before_deploy:
  # Set up git user name and tag this commit
  #- git config --local user.name "YOUR GIT USER NAME"
  #- git config --local user.email "YOUR GIT USER EMAIL"
  - git tag "$(date +'%Y%m%d_%H%M%S')-$(git log --format=%h -1)"
  - tar cjvf public.tar.bz2 public/

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: public
    on:
      branch: master
    target-branch: gh-pages
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: public.tar.bz2
    skip_cleanup: true
    on:
      branch: master

# whitelist
branches:
  only:
    - master 
